In [6]:
# Carefully watch numpy logo and check what it is.
# It 3d matrix with N
import numpy as np

CreatingArray = np.array([1,2,4])
CreatingArray #print array


dtype('int32')

In [7]:
CreatingArray.dtype


dtype('int32')

In [ ]:
CreatingArray.shape


dtype('int32')

<h1>Array creation from other python datastructure</h1>

In [8]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
listarray.shape


(3, 3)

In [13]:
listarray.dtype

dtype('int32')

<h1>Array from set</h1>

In [21]:
s = np.array(((23,45,43)))
l = np.array([2,34,5,6,7])
d = np.array({"kd":2,"dfd":4})


array({'kd': 2, 'dfd': 4}, dtype=object)

In [24]:
s


array([23, 45, 43])

In [28]:
d
# Here dtype is given as object not useful creta it in int format

array({'kd': 2, 'dfd': 4}, dtype=object)

<h1>Creating random arrays</h1>

In [30]:
ArrayOfZeros = np.ones((4,5)) #Creates a array filled with 1 in form 4 rows and 5 columns
ArrayOfZeros

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [39]:
range = np.arange(200)
range

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [42]:
lspace = np.linspace(1,5,8)
lspace # gives element from starting to end with equal parts 

array([1.        , 1.57142857, 2.14285714, 2.71428571, 3.28571429,
       3.85714286, 4.42857143, 5.        ])

In [49]:
emp = np.empty((4,7))
emp.ndim
emp

array([[6.01391519e-154, 1.30371153e-076, 3.76112667e+179,
        3.44357011e-086, 5.93393717e-038, 4.57669086e-072,
        2.73825610e-057],
       [1.02455757e+136, 6.01347002e-154, 1.83289973e-076,
        9.73480488e-072, 2.63344494e-052, 1.08539814e-071,
        4.85107179e-033],
       [3.57280233e-062, 6.01391519e-154, 1.30371153e-076,
        3.59903622e+179, 3.44357011e-086, 4.66535125e-062,
        4.57669086e-072],
       [6.37549931e-067, 1.02455757e+136, 6.01347002e-154,
        1.83289973e-076, 9.73480488e-072, 2.63344494e-052,
        1.08539815e-071]])